spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306
mybatis-plus:
  config-location:
  mapper-locations:
  configuration:
    map-underscore-to-camel-case: true